<section class="footer">
    <footer>
        <h4>CREDITS</h4>
        <a href="mailto:103995439@student.swin.edu.au"><p>Anh</p></a>
        <a href="mailto:104024567@student.swin.edu.au"><p>Enton</p></a>
        <a href="mailto:103181157@student.swin.edu.au"><p>Nam</p></a>
        <a href="mailto:104026152@student.swin.edu.au"><p>Oscar</p></a>
        <a href="mailto:102649968@student.swin.edu.au"><p>Thanh</p></a>
        <h5>&copy; 2022 <em>Team Cafe Sua Da</em></h5>
    </footer>
</section>