<section>
		<div class="topnav">
			<strong><a href="index.php">HOME</a></strong>
			<strong><a href="topic.php" class="active">TOPIC</a></strong>
			<strong><a href="quiz.php">QUIZ</a></strong>
			<strong><a href="enhancements.php">ENHANCEMENTS</a></strong>
			<strong><a href="phpenhancements.php">ENHANCEMENTS 2</a></strong>
			<strong><a href="admin.php">MANAGE</a></strong>
		</div>
</section>