<meta charset="utf-8" />
<meta name="description" content="Assignment 2 COS10026" />
<meta name="keywords" content="HTML5,PHP" />
<link rel="icon" href="./images/ico.jpeg">
<meta name="author" content="Tran Duc Anh Dang, Nguyen Nam Tung, Tran Quang Thanh" />
<link href="styles/style.css" rel="stylesheet"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>    
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;1,400&display=swap" rel="stylesheet">